string1 = input("Please enter the first string: ")
string2 = input("Please enter the second string: ")
string3 = input("Please enter the third string: ")
#string1.upper()
#string2.upper()
#string3.upper()
print(string1.upper() + string2.upper() + string3.upper())